;; NEAR Vault Contract v6 — multi-lock per owner (nonce-indexed)

(define (lock)
  (let ((input (near/input))
        (owner (json/get "owner" input))
        (dur (near/json_get_int "duration_ns"))
        (ts (near/block_timestamp)))
    (if (= (str-len owner) 0)
      (near/return "missing owner")
      (if (< dur 60000000000)
        (near/return "duration too short")
        (let ((unlock (+ ts dur))
              (counter_key (str-cat "lock:" owner ":next_id"))
              (nonce (near/load counter_key))
              (id (if (= nonce 0) 1 nonce))
              (next (+ id 1))
              (str_id (to-string id))
              (kd (str-cat "lock:" owner ":" str_id ":amt"))
              (ku (str-cat "lock:" owner ":" str_id ":time")))
          (begin
            (near/attached_deposit)
            (near/store_deposit kd)
            (near/store ku unlock)
            (near/store counter_key next)
            (near/return str_id)
          )
        )
      )
    )
  )
)

(define (claim)
  (let ((input (near/input))
        (caller (near/predecessor_account_id))
        (owner (json/get "owner" input))
        (lock_id (json/get "lock_id" input))
        (str_id (if (= (str-len lock_id) 0) "0" lock_id))
        (kd (str-cat "lock:" owner ":" str_id ":amt"))
        (ku (str-cat "lock:" owner ":" str_id ":time"))
        (lo (near/load_deposit kd)))
    (if (= lo 0)
      (near/return "no lock found")
      (if (str_eq caller owner)
        (let ((ts (near/block_timestamp))
              (unlock_ts (near/load ku)))
          (if (< ts unlock_ts)
            (near/return "not unlocked")
            (begin
              (near/load_deposit_high)
              (near/storage_remove kd)
              (near/storage_remove ku)
              (near/claim_deposit owner)
              (near/return "claimed")
            )
          )
        )
        (near/return "not owner")
      )
    )
  )
)

(define (lock_ft)
  (let ((input (near/input))
        (owner (json/get "receiver_id" input))
        (token (json/get "token" input))
        (amount (json/get "amount" input))
        (dur (near/json_get_int "duration_ns"))
        (ts (near/block_timestamp)))
    (if (< dur 60000000000)
      (near/return "duration too short")
      (let ((unlock (+ ts dur))
            (counter_key (str-cat "ft:" owner ":" token))
            (counter_full (str-cat counter_key ":next_id"))
            (nonce (near/load counter_full))
            (id (if (= nonce 0) 1 nonce))
            (next (+ id 1))
            (str_id (to-string id))
            (ka (str-cat "ft:" owner ":" token ":" str_id ":amt"))
            (kt (str-cat "ft:" owner ":" token ":" str_id ":time")))
        (begin
          (near/store-bytes ka amount)
          (near/store kt unlock)
          (near/store counter_full next)
          (near/return str_id)
        )
      )
    )
  )
)

(define (claim_ft)
  (let ((input (near/input))
        (caller (near/predecessor_account_id))
        (owner (json/get "receiver_id" input))
        (token (json/get "token" input))
        (lock_id (json/get "lock_id" input))
        (str_id (if (= (str-len lock_id) 0) "0" lock_id))
        (ka (str-cat "ft:" owner ":" token ":" str_id ":amt"))
        (kt (str-cat "ft:" owner ":" token ":" str_id ":time"))
        (existing (near/load-bytes ka)))
    (if (= (str-len existing) 0)
      (near/return "no ft lock found")
      (if (str_eq caller owner)
        (let ((ts (near/block_timestamp))
              (unlock_ts (near/load kt)))
          (if (< ts unlock_ts)
            (near/return "not unlocked")
            (begin
              (near/storage_remove ka)
              (near/storage_remove kt)
              (near/return "ft claimed")
            )
          )
        )
        (near/return "not owner")
      )
    )
  )
)

(export "lock" lock)
(export "claim" claim)
(export "lock_ft" lock_ft)
(export "claim_ft" claim_ft)
